[versions]
androidGradlePlugin = "8.4.1"
kotlin = "2.0.0"
ksp = "2.0.0-1.0.21"
javaVersion = "17"

coroutine = "1.6.1"
ktor = "1.6.4"
lifecycle = "2.5.1"
navigation = "2.5.3"


[libraries]
androidxAppcompat = { module = "androidx.appcompat:appcompat", version = "1.3.1" }
coil = { module = "io.coil-kt:coil", version = "1.3.2" }
androidxConstraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.1" }
androidxCoreKtx = { module = "androidx.core:core-ktx", version = "1.6.0" }
androidxTestEspressoCore = { module = "androidx.test.espresso:espresso-core", version = "3.4.0" }
androidxTextJunit = { module = "androidx.test.ext:junit", version = "1.1.3" }
androidGradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
junit = { module = "junit:junit", version = "4.13.2" }
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinxCoroutineAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutine" }
ktorClientAndroid = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
androidxLifecycleLivedataKtx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidxLifecycleRuntimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidxLifecycleViewmodelKtx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
material = { module = "com.google.android.material:material", version = "1.4.0" }
androidxNavigationFragmentKtx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
androidxNavigationSafeArgs = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigation" }
androidxNavigationUiKtx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
androidxRecyclerview = { module = "androidx.recyclerview:recyclerview", version = "1.2.1" }
kotestAssertion = { module = "io.kotest:kotest-assertions-core", version = "5.9.0" }
kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.7.0-RC" }

[plugins]
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
