name: run ktlint
on: pull_request
jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Ktint set up"
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.50.0/ktlint &&
          chmod a+x ktlint && 
          sudo mv ktlint /usr/local/bin/
      - run: |
          ktlint "*/src/**/*.kt" "!*/src/*Test/*" "!*/src/*test/*" "!*/src/test/*"
