name: "cleanup pull request"
on:
  pull_request:
    types:
      - closed

jobs:
  delete-compare-branch:
    runs-on: ubuntu-latest
    name: "cleanup compare diff branch"
    steps:
      - uses: actions/checkout@v4

      - name: Cleanup outdated companion branches
        shell: bash
        run: |
          git push origin --delete "companion_${{ github.head_ref }}"
